import Navbar from "@/components/navbar";
import Footer from '@/components/footer';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <div className="w-full mx-auto p-4 flex-grow flex flex-col">
        <Navbar />
          <div className="mt-8  w-4xl flex-grow flex flex-col">
            {children}
            
          </div>
          <Footer className="bottom-0 w-full" />
        </div>
      </body>
    </html>
  );
}